"""Release documents must agree with the artifact, and with each other.

Three documents described this release and disagreed. Programme recall was
written as 4/10 in one place and 8/10 in another. Claims were 27 and 51.
Accepted pages were 12 and 20. The backend test count was 772, then 977, and
the commit count said 33 when it was 34. Every one of those numbers had been
true when it was written, and none was checked again.

Prose cannot be checked, so the numbers now live in
`artifacts/release-evidence.json`, generated by `scripts/release_evidence.py`
from commands it actually ran. These tests fail when a document disagrees with
it.

The rule that matters most is the last one: a document may not say READY while
a gate is open. That is not a formatting concern. It is the difference between
a release that was verified and one that was described.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent.parent
ARTIFACT = ROOT / "artifacts" / "release-evidence.json"
#: Documents that describe the *current* state and must therefore agree with
#: the artifact. README is here because it was quoting a recall of 1/10 and 768
#: tests long after both were false, and nothing was reading it.
DOCUMENTS = [
    ROOT / "README.md",
    ROOT / "RELEASE_CHECKLIST.md",
    ROOT / "docs" / "evidence" / "RELEASE-EVIDENCE-2026-08-29.md",
    ROOT / "docs" / "LIVE_DISCOVERY_REPORT.md",
]


@pytest.fixture(scope="module")
def artifact() -> dict:
    """The release evidence. Its absence is a failure, not a skip.

    Skipping here meant a repository with no evidence at all produced a green
    release-verification suite. Missing evidence is the loudest thing this file
    can find, and it was the quietest.
    """
    assert ARTIFACT.exists(), (
        f"{ARTIFACT.relative_to(ROOT)} does not exist. Release verification "
        "cannot pass without it; run scripts/release_evidence.py."
    )
    return json.loads(ARTIFACT.read_text())


@pytest.fixture(scope="module")
def documents() -> dict[Path, str]:
    return {p: p.read_text() for p in DOCUMENTS if p.exists()}


class TestTheArtifactIsInternallyHonest:
    def test_the_gates_were_measured_against_a_committed_tree(self, artifact: dict):
        """A gate result describes whatever was on disk when it ran.

        `working_tree_clean` was a single boolean and it was always `false`,
        because generating the artifact writes the artifact — so the field cast
        doubt on every gate beside it and distinguished nothing. What a reader
        needs to know is narrower: did any *source* differ from HEAD? If it
        did, these numbers describe a tree that is in no commit and cannot be
        reproduced from one.
        """
        tree = artifact["working_tree"]
        assert tree["uncommitted_paths"] == [], (
            "the gates were measured against uncommitted changes, so they "
            f"describe no commit: {tree['uncommitted_paths'][:5]}"
        )
        assert tree["clean_ignoring_generated_outputs"] is True

    def test_the_verdict_follows_from_the_gates(self, artifact: dict):
        """READY is computed, not asserted. A document cannot talk its way
        past a failing or unrun gate if the verdict is derived from them."""
        open_gates = artifact["open_gates"]
        expected = (
            "READY"
            if not open_gates["failing"]
            and not open_gates["not_run"]
            and not open_gates.get("product_thresholds")
            else "NOT READY"
        )
        assert artifact["verdict"] == expected

    def test_product_thresholds_can_hold_the_verdict_on_their_own(self, artifact: dict):
        """Green technical gates do not earn READY. A release that builds,
        tests and deploys perfectly and cannot answer an applicant's questions
        is not ready; it is shippable, which is a different word."""
        open_gates = artifact["open_gates"]
        if open_gates.get("product_thresholds"):
            assert artifact["verdict"] == "NOT READY"

    def test_a_gate_that_did_not_run_is_not_a_pass(self, artifact: dict):
        for name, gate in artifact["gates"].items():
            if gate["result"] == "not_run":
                assert gate["exit_code"] is None, name
                assert gate["detail"], f"{name} says not_run without saying why"

    def test_every_gate_records_the_command_it_ran(self, artifact: dict):
        for name, gate in artifact["gates"].items():
            assert gate.get("command"), name

    def test_open_gates_match_the_gate_results(self, artifact: dict):
        failing = {k for k, v in artifact["gates"].items() if v["result"] == "fail"}
        not_run = {k for k, v in artifact["gates"].items() if v["result"] == "not_run"}
        assert set(artifact["open_gates"]["failing"]) == failing
        assert set(artifact["open_gates"]["not_run"]) == not_run


class TestTheDocumentsAgreeWithTheArtifact:
    def test_no_document_claims_ready_while_a_gate_is_open(
        self, artifact: dict, documents: dict[Path, str]
    ):
        if artifact["verdict"] == "READY":
            # Nothing to guard against, and nothing to hide either.
            return
        for path, text in documents.items():
            for line in text.splitlines():
                stripped = re.sub(r"[*_`]", "", line).strip()
                if re.match(r"^(current )?verdict:?\s*ready\b", stripped, re.IGNORECASE):
                    raise AssertionError(
                        f"{path.name} states READY while these gates are open: "
                        f"{artifact['open_gates']}"
                    )

    def test_the_commit_count_matches(self, artifact: dict, documents: dict[Path, str]):
        """Off by one at the last check, because it was written before the
        final commit and never re-read."""
        actual = artifact["commits_since_base"]
        for path, text in documents.items():
            for stated in re.findall(r"(\d+) commits on top of", text):
                assert int(stated) == actual, (
                    f"{path.name} says {stated} commits, the repository has {actual}"
                )

    def test_the_backend_test_count_matches(
        self, artifact: dict, documents: dict[Path, str]
    ):
        actual = artifact["counts"]["backend_tests"]
        # Only rows running the *whole* backend suite. Two earlier versions
        # were too loose and both failures were the test's fault, not the
        # document's: the first matched any "**PASS** — N passed" and read the
        # frontend row's 56 as a backend count; the second matched any command
        # containing "pytest" and read `pytest -k ssrf`'s 90. A row that runs a
        # subset is reporting a subset, and comparing it to the total is
        # meaningless.
        row = re.compile(
            r"^\|[^|]*\|[^|]*\bpytest\b(?![^|]*(?:-k|tests/))[^|]*\|[^|]*?(\d+) passed",
            re.M,
        )
        for path, text in documents.items():
            for stated in row.findall(text):
                # A missing count is not a failure of *this* suite.
                #
                # It used to be asserted directly — "the artifact records no
                # count, so the run that produced it did not pass" — which made
                # this test's own outcome depend on a previous run's. Once the
                # count was ever missing it could never come back: the test
                # failed, so the suite failed, so the next artifact recorded no
                # count either. A check that can only pass if it has already
                # passed is not evidence of anything.
                #
                # The property actually worth enforcing survives without the
                # circularity, and is the stronger half: a document may not
                # state a number the artifact cannot support. That is what
                # caught the README carrying 768 tests long after it was false.
                assert actual is not None, (
                    f"{path.name} states {stated} backend tests while the "
                    "artifact records no count at all — the run that produced "
                    "it did not pass, so the document is quoting nothing"
                )
                assert int(stated) == actual, (
                    f"{path.name} says {stated} backend tests, the run counted {actual}"
                )

    def test_the_container_gate_is_never_described_as_passing(
        self, artifact: dict, documents: dict[Path, str]
    ):
        """A document may call this gate PASS only when something observed it.

        It cannot be measured on this machine — there is no container runtime —
        so the artifact carries CI's attestation instead, and that is only
        honoured when its SHA matches the commit the artifact describes. A
        document asserting PASS without one would be describing something
        nobody watched.
        """
        gate = artifact["gates"]["container_runtime"]
        if gate["result"] == "pass":
            # Asserted, not skipped. This skip was the single runtime skip in
            # the suite, and it made every report that said "skips 0" wrong.
            # A passing gate has something to check: that an attestation for
            # *this* commit is why it passed.
            assert gate.get("head_sha"), (
                "the container gate is recorded as passing with no evidence "
                "naming the commit it passed at"
            )
            assert gate["head_sha"] == artifact["head"], (
                f"the container gate is recorded for head {gate['head_sha'][:7]}, "
                f"not for {artifact['head'][:7]}"
            )
            # Either kind of evidence is acceptable and each says what it is.
            # The full attestation carries CI's own bytes and the trees; the
            # check-run conclusion is the public API's verdict, which is all
            # that can be read without repository credentials.
            if gate.get("raw_attestation"):
                assert len(gate.get("attestation_sha256", "")) == 64
                # On a pull_request the commit CI checked out is a synthetic
                # merge, and calling it the branch SHA is what went wrong.
                assert gate.get("tested_sha"), (
                    "the attestation does not say what was tested"
                )
            else:
                assert gate.get("raw_observation"), (
                    "the container gate passed with neither an attestation nor "
                    "a recorded CI observation"
                )
                assert gate.get("evidence"), "the kind of evidence is not stated"
            return
        for path, text in documents.items():
            for line in text.splitlines():
                if "compose_smoke" in line or "container-runtime" in line.lower():
                    assert "**PASS**" not in line, (
                        f"{path.name} calls the container gate PASS: {line.strip()[:120]}"
                    )


class TestTheLiveNumbersAgree:
    def test_the_documents_do_not_contradict_the_measured_recall(
        self, artifact: dict, documents: dict[Path, str]
    ):
        live = artifact.get("live_discovery")
        assert live and live.get("median_programme_pages") is not None, (
            "the artifact carries no live discovery measurement; release "
            "verification cannot pass on unmeasured recall"
        )
        median = live["median_programme_pages"]
        # Only statements about the median *now*. A before/after table
        # legitimately records what an earlier run produced, and the first
        # version of this test read "Session start | 7/10" as a contradiction —
        # it would have pushed someone to delete true history to get to green,
        # which is the opposite of what this file is for.
        pattern = re.compile(
            r"median(?:\s+of\s+\d+\s+runs)?[^.\n|]{0,30}?\**(\d+)\s*/\s*10"
            r"|\bmedian\s+(\d+)\b",
            re.I,
        )
        for path, text in documents.items():
            for first, second in pattern.findall(text):
                stated = first or second
                assert int(stated) == median, (
                    f"{path.name} states a median of {stated}; the measured "
                    f"median is {median}"
                )

    def test_a_zero_tolerance_false_positive_is_never_reported_as_acceptable(
        self, artifact: dict
    ):
        live = artifact.get("live_discovery")
        assert live, "the artifact carries no live discovery measurement"
        for run in live["runs"]:
            assert run["false_positives"] == 0, (
                "a run recorded a zero-tolerance false positive; no document "
                "may describe this release as meeting its bar"
            )


class TestNoDocumentHasBlanksOrStaleState:
    """The checks that were missing, each for a defect that survived the ones
    that were here.

    Every earlier rule was conditional: "if the regex finds a number, it must
    match". A blank finds no number, so `**PASS** —  passed` passed. A stale
    SHA is not a number, so `0af7daa` passed. A README claiming recall of 1/10
    was never read at all.
    """

    #: Placeholders that mean a measured value was meant to be here and is not.
    #: Checked with backtick spans removed: a document explaining that
    #: `**PASS** —  passed` once appeared is describing the defect, not
    #: containing it.
    BLANKS = (
        re.compile(r"\*\*PASS\*\* —\s*passed"),
        re.compile(r"\|\s*Tests\s*\|\s*backend"),
    )

    #: A gate row is a verdict and the evidence for it: `**PASS** — 1859 passed`.
    #: A `sed` with an empty variable wrote `**PASS** —  passed` into six rows
    #: of the evidence document, and the count that should have been there was
    #: simply gone.
    #:
    #: The discriminator is the missing *number*, not the words. A blanket
    #: `—\s+passed` also matched ordinary prose — "a project list — passed as a
    #: programme on two degree words" — which is a sentence, not a gate.
    #: The defect is a *count* that went missing, and the shape it leaves is
    #: "passed" sitting immediately after the dash with nothing before it:
    #: `**PASS** —  passed`. Anything else between the dash and the word is a
    #: tool saying something in English — `**PASS** — All checks passed!` is
    #: ruff, and it has no count to lose.
    GATE_VERDICT_WITHOUT_COUNT = re.compile(
        r"\*\*(?:PASS|FAIL|BLOCKED)\*\*\s*—\s*passed\b"
    )

    @classmethod
    def _verdict_without_a_count(cls, line: str) -> str | None:
        match = cls.GATE_VERDICT_WITHOUT_COUNT.search(line)
        return match.group(0) if match else None

    #: Markers of unfinished work, in the shapes an actual one takes: followed
    #: by a colon or a dash, or opening a list item.
    #:
    #: A bare word match was wrong in both directions. It flagged a checklist
    #: row quoting `grep -rn "TODO\|FIXME"`, and a gate whose title is "No
    #: TODO / FIXME in a production path" — both of which report the *absence*
    #: of unfinished work. Backtick spans are stripped as well.
    UNFINISHED = re.compile(
        r"(?:^|\s)[-*]?\s*(?:TODO|TBD|XXX|FIXME)\s*[:\-—]", re.IGNORECASE
    )

    @staticmethod
    def _without_code(line: str) -> str:
        r"""Backtick spans quote commands and output, so a checklist row saying
        `grep -rn "TODO\|FIXME"` is describing a check rather than leaving one
        undone. The prose around the code is what these rules are about."""
        return re.sub(r"`[^`]*`", "", line)

    def test_no_current_document_contains_a_blank_value(
        self, documents: dict[Path, str]
    ):
        for path, text in documents.items():
            for raw in text.splitlines():
                stripped = self._without_code(raw)
                for blank in self.BLANKS:
                    assert not blank.search(stripped), (
                        f"{path.name} has a placeholder where a measured value "
                        f"belongs: {raw.strip()[:120]}"
                    )
                assert self._verdict_without_a_count(stripped) is None, (
                    f"{path.name} states a gate verdict with no count behind "
                    f"it: {raw.strip()[:120]}"
                )
                assert not self.UNFINISHED.search(self._without_code(raw)), (
                    f"{path.name} records unfinished work: {raw.strip()[:120]}"
                )

    def test_no_current_document_quotes_a_stale_commit(
        self, artifact: dict, documents: dict[Path, str]
    ):
        """A document may cite an older commit as history — "it failed at
        `a669496`" — but not as the state of the branch now."""
        head = artifact["head"][:7]
        present_tense = re.compile(
            r"(?:verified|measured|as of|currently|at HEAD)[^.\n|]{0,40}`([0-9a-f]{7,40})`",
            re.IGNORECASE,
        )
        for path, text in documents.items():
            for stated in present_tense.findall(text):
                assert artifact["head"].startswith(stated) or stated.startswith(head), (
                    f"{path.name} describes the current state at {stated}, "
                    f"but HEAD is {head}"
                )

    def test_a_gate_is_not_both_passing_and_blocked(self, documents: dict[Path, str]):
        """`RELEASE_CHECKLIST.md` said gate 22 was PASS in its table and
        BLOCKED in its prose, which is not a formatting problem: a reader takes
        whichever they happen to read."""
        checklist = next(
            (t for p, t in documents.items() if p.name == "RELEASE_CHECKLIST.md"), None
        )
        if checklist is None:
            return
        for line in checklist.splitlines():
            assert not ("**PASS**" in line and "**BLOCKED**" in line), line.strip()[:120]

    def test_the_test_counts_in_every_document_agree_with_the_artifact(
        self, artifact: dict, documents: dict[Path, str]
    ):
        """Not only the evidence file. The README quoted 768 backend tests long
        after there were 1859, and nothing checked it."""
        backend = artifact["counts"]["backend_tests"]
        stale = re.compile(r"\b(\d{3,5}) (?:backend )?tests?\b|\bpytest`? +(\d{3,5})\b")
        for path, text in documents.items():
            for a, b in stale.findall(text):
                stated = int(a or b)
                # Four-digit-plus numbers in these documents are test counts.
                if stated < 100:
                    continue
                assert stated == backend, (
                    f"{path.name} states {stated} tests; the artifact counted {backend}"
                )
