"""Release documents must agree with the artifact, and with each other.

Three documents described this release and disagreed. Programme recall was
written as 4/10 in one place and 8/10 in another. Claims were 27 and 51.
Accepted pages were 12 and 20. The backend test count was 772, then 977, and
the commit count said 33 when it was 34. Every one of those numbers had been
true when it was written, and none was checked again.

Prose cannot be checked, so the numbers now live in
`artifacts/release-evidence.json`, generated by `scripts/release_evidence.py`
from commands it actually ran. These tests fail when a document disagrees with
it.

The rule that matters most is the last one: a document may not say READY while
a gate is open. That is not a formatting concern. It is the difference between
a release that was verified and one that was described.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent.parent
ARTIFACT = ROOT / "artifacts" / "release-evidence.json"
DOCUMENTS = [
    ROOT / "RELEASE_CHECKLIST.md",
    ROOT / "docs" / "evidence" / "RELEASE-EVIDENCE-2026-08-29.md",
    ROOT / "docs" / "LIVE_DISCOVERY_REPORT.md",
]


@pytest.fixture(scope="module")
def artifact() -> dict:
    if not ARTIFACT.exists():
        pytest.skip(
            f"{ARTIFACT.relative_to(ROOT)} has not been generated; "
            "run scripts/release_evidence.py"
        )
    return json.loads(ARTIFACT.read_text())


@pytest.fixture(scope="module")
def documents() -> dict[Path, str]:
    return {p: p.read_text() for p in DOCUMENTS if p.exists()}


class TestTheArtifactIsInternallyHonest:
    def test_the_verdict_follows_from_the_gates(self, artifact: dict):
        """READY is computed, not asserted. A document cannot talk its way
        past a failing or unrun gate if the verdict is derived from them."""
        open_gates = artifact["open_gates"]
        expected = "READY" if not open_gates["failing"] and not open_gates["not_run"] else "NOT READY"
        assert artifact["verdict"] == expected

    def test_a_gate_that_did_not_run_is_not_a_pass(self, artifact: dict):
        for name, gate in artifact["gates"].items():
            if gate["result"] == "not_run":
                assert gate["exit_code"] is None, name
                assert gate["detail"], f"{name} says not_run without saying why"

    def test_every_gate_records_the_command_it_ran(self, artifact: dict):
        for name, gate in artifact["gates"].items():
            assert gate.get("command"), name

    def test_open_gates_match_the_gate_results(self, artifact: dict):
        failing = {k for k, v in artifact["gates"].items() if v["result"] == "fail"}
        not_run = {k for k, v in artifact["gates"].items() if v["result"] == "not_run"}
        assert set(artifact["open_gates"]["failing"]) == failing
        assert set(artifact["open_gates"]["not_run"]) == not_run


class TestTheDocumentsAgreeWithTheArtifact:
    def test_no_document_claims_ready_while_a_gate_is_open(
        self, artifact: dict, documents: dict[Path, str]
    ):
        if artifact["verdict"] == "READY":
            pytest.skip("nothing to guard against while every gate passes")
        for path, text in documents.items():
            for line in text.splitlines():
                stripped = re.sub(r"[*_`]", "", line).strip()
                if re.match(r"^(current )?verdict:?\s*ready\b", stripped, re.IGNORECASE):
                    raise AssertionError(
                        f"{path.name} states READY while these gates are open: "
                        f"{artifact['open_gates']}"
                    )

    def test_the_commit_count_matches(self, artifact: dict, documents: dict[Path, str]):
        """Off by one at the last check, because it was written before the
        final commit and never re-read."""
        actual = artifact["commits_since_base"]
        for path, text in documents.items():
            for stated in re.findall(r"(\d+) commits on top of", text):
                assert int(stated) == actual, (
                    f"{path.name} says {stated} commits, the repository has {actual}"
                )

    def test_the_backend_test_count_matches(
        self, artifact: dict, documents: dict[Path, str]
    ):
        actual = artifact["counts"]["backend_tests"]
        if actual is None:
            pytest.skip("the artifact records no backend test count")
        # Only rows running the *whole* backend suite. Two earlier versions
        # were too loose and both failures were the test's fault, not the
        # document's: the first matched any "**PASS** — N passed" and read the
        # frontend row's 56 as a backend count; the second matched any command
        # containing "pytest" and read `pytest -k ssrf`'s 90. A row that runs a
        # subset is reporting a subset, and comparing it to the total is
        # meaningless.
        row = re.compile(
            r"^\|[^|]*\|[^|]*\bpytest\b(?![^|]*(?:-k|tests/))[^|]*\|[^|]*?(\d+) passed",
            re.M,
        )
        for path, text in documents.items():
            for stated in row.findall(text):
                assert int(stated) == actual, (
                    f"{path.name} says {stated} backend tests, the run counted {actual}"
                )

    def test_the_container_gate_is_never_described_as_passing(
        self, artifact: dict, documents: dict[Path, str]
    ):
        """The one gate that has never run on this machine. A document calling
        it PASS would be describing something that has not happened."""
        if artifact["gates"]["container_runtime"]["result"] == "pass":
            pytest.skip("the container gate has actually run")
        for path, text in documents.items():
            for line in text.splitlines():
                if "compose_smoke" in line or "container-runtime" in line.lower():
                    assert "**PASS**" not in line, (
                        f"{path.name} calls the container gate PASS: {line.strip()[:120]}"
                    )


class TestTheLiveNumbersAgree:
    def test_the_documents_do_not_contradict_the_measured_recall(
        self, artifact: dict, documents: dict[Path, str]
    ):
        live = artifact.get("live_discovery")
        if not live or live.get("median_programme_pages") is None:
            pytest.skip("the artifact carries no canary measurement")
        median = live["median_programme_pages"]
        # Only statements about the median *now*. A before/after table
        # legitimately records what an earlier run produced, and the first
        # version of this test read "Session start | 7/10" as a contradiction —
        # it would have pushed someone to delete true history to get to green,
        # which is the opposite of what this file is for.
        pattern = re.compile(
            r"median(?:\s+of\s+\d+\s+runs)?[^.\n|]{0,30}?\**(\d+)\s*/\s*10"
            r"|\bmedian\s+(\d+)\b",
            re.I,
        )
        for path, text in documents.items():
            for first, second in pattern.findall(text):
                stated = first or second
                assert int(stated) == median, (
                    f"{path.name} states a median of {stated}; the measured "
                    f"median is {median}"
                )

    def test_a_zero_tolerance_false_positive_is_never_reported_as_acceptable(
        self, artifact: dict
    ):
        live = artifact.get("live_discovery")
        if not live:
            pytest.skip("the artifact carries no canary measurement")
        for run in live["runs"]:
            assert run["false_positives"] == 0, (
                "a run recorded a zero-tolerance false positive; no document "
                "may describe this release as meeting its bar"
            )
