/**
 * Builds src/lib/globe-land.ts - the land of the globe as dots - and checks
 * src/lib/globe-places.json against the country outlines.
 *
 * Run once, when either changes. Its three packages are not dependencies of
 * the app, so install them without saving:
 *
 *   npm i --no-save world-atlas@2 topojson-client@3 d3-geo@3
 *   node scripts/gen-globe.mjs
 *
 * Land: Natural Earth 1:50m (public domain) via world-atlas (ISC). Dots are
 * an even Fibonacci lattice over the sphere, kept where they fall on land,
 * packed as Int16 pairs (latitude and longitude times 100) in base64: about
 * 45 KB (33 KB gzipped), loaded as a chunk of its own the first time a globe
 * is drawn, and no geometry library at all.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { feature } from 'topojson-client';
import { geoContains, geoDistance } from 'd3-geo';

const require = createRequire(import.meta.url);
const land = feature(require('world-atlas/land-50m.json'), require('world-atlas/land-50m.json').objects.land);
const countries = require('world-atlas/countries-50m.json');
const countryShapes = feature(countries, countries.objects.countries).features;

const N = 32000;
const golden = Math.PI * (3 - Math.sqrt(5));
const dots = [];
for (let i = 0; i < N; i += 1) {
  const y = 1 - (i / (N - 1)) * 2;
  const lat = (Math.asin(y) * 180) / Math.PI;
  if (lat < -58) continue; // Antarctica is never in view and never a destination
  const lon = ((((i * golden) * 180) / Math.PI) % 360 + 540) % 360 - 180;
  if (geoContains(land, [lon, lat])) dots.push([lat, lon]);
}
const packed = new Int16Array(dots.length * 2);
dots.forEach(([lat, lon], i) => { packed[i * 2] = Math.round(lat * 100); packed[i * 2 + 1] = Math.round(lon * 100); });
const b64 = Buffer.from(packed.buffer).toString('base64');
writeFileSync(new URL('../src/lib/globe-land.ts', import.meta.url), `/**
 * The globe's land as ${dots.length} dots, generated by scripts/gen-globe.mjs
 * from Natural Earth 1:50m (public domain). Int16 pairs, latitude and
 * longitude times 100, in base64. Do not edit by hand.
 */

export const LAND_DOT_COUNT = ${dots.length};
export const LAND_DOTS = '${b64}';
`);
console.log(`land: ${dots.length} dots, ${b64.length} base64 chars`);

// Every place must sit inside its country, or within 60 km of it (a coastal
// city on a simplified coastline). Natural Earth names a few differently.
const NE_NAME = {
  'United States': 'United States of America', 'Czech Republic': 'Czechia', Czechia: 'Czechia',
  Turkiye: 'Turkey', 'Hong Kong': 'Hong Kong', Russia: 'Russia',
};
const places = JSON.parse(readFileSync(new URL('../src/lib/globe-places.json', import.meta.url), 'utf8'));
const EARTH_KM = 6371;
let bad = 0;
for (const p of [...places.cities, ...places.homes]) {
  const name = NE_NAME[p.country] ?? p.country;
  const shape = countryShapes.find((f) => f.properties.name === name);
  if (!shape) { console.log(`NO OUTLINE  ${p.country} (${p.city})`); bad += 1; continue; }
  const point = [p.lon, p.lat];
  if (geoContains(shape, point)) continue;
  // Distance to the nearest outline vertex.
  let nearest = Infinity;
  const walk = (c) => { if (typeof c[0] === 'number') nearest = Math.min(nearest, geoDistance(point, c) * EARTH_KM); else c.forEach(walk); };
  walk(shape.geometry.coordinates);
  if (nearest > 60) { console.log(`OUTSIDE     ${p.city}, ${p.country}: ${nearest.toFixed(0)} km from the outline`); bad += 1; }
}
console.log(bad ? `${bad} place(s) failed` : `all ${places.cities.length + places.homes.length} places check out`);
process.exit(bad ? 1 : 0);
