"""Initial schema.

Everything the application needs: applicant profiles, research runs and their
results, the claim and conflict evidence tables, the audit trail, the durable
job queue, and the schema-version stamp.

Deletion cascades are declared at the database level *as well as* in the ORM.
The ORM cascade is the guarantee (a pragma or a driver setting cannot be relied
on); the database constraint is the backstop.

Revision ID: bb9a7d0ed5c3
Revises: 
Create Date: 2026-08-28 13:29:01.785506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb9a7d0ed5c3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applicant_profiles',
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_events',
    sa.Column('actor', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_entity', 'audit_events', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_table('jobs',
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('queue', sa.String(length=40), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=True),
    sa.Column('idempotency_key', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('worker_id', sa.String(length=80), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_jobs_claimable', 'jobs', ['status', 'available_at', 'priority'], unique=False)
    op.create_index('ix_jobs_lease', 'jobs', ['status', 'lease_expires_at'], unique=False)
    op.create_index('ix_jobs_run', 'jobs', ['run_id'], unique=False)
    op.create_table('schema_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_runs',
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('stage', sa.String(length=40), nullable=False),
    sa.Column('demo_mode', sa.Boolean(), nullable=False),
    sa.Column('candidate_limit', sa.Integer(), nullable=True),
    sa.Column('verify_limit', sa.Integer(), nullable=True),
    sa.Column('cancelled', sa.Boolean(), nullable=False),
    sa.Column('candidates_found', sa.Integer(), nullable=False),
    sa.Column('programs_verified', sa.Integer(), nullable=False),
    sa.Column('pages_checked', sa.Integer(), nullable=False),
    sa.Column('pages_failed', sa.Integer(), nullable=False),
    sa.Column('claims_recorded', sa.Integer(), nullable=False),
    sa.Column('stage_state', sa.JSON(), nullable=False),
    sa.Column('fetch_tiers', sa.JSON(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('retry_urls', sa.JSON(), nullable=False),
    sa.Column('settings_snapshot', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('worker_id', sa.String(length=64), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recovery_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['applicant_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_runs_profile_id'), 'research_runs', ['profile_id'], unique=False)
    op.create_index(op.f('ix_research_runs_stage'), 'research_runs', ['stage'], unique=False)
    op.create_index(op.f('ix_research_runs_worker_id'), 'research_runs', ['worker_id'], unique=False)
    op.create_table('claims',
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('result_id', sa.String(length=32), nullable=True),
    sa.Column('claim_type', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_specificity', sa.String(length=40), nullable=False),
    sa.Column('accessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_claim_type'), 'claims', ['claim_type'], unique=False)
    op.create_index(op.f('ix_claims_result_id'), 'claims', ['result_id'], unique=False)
    op.create_index(op.f('ix_claims_run_id'), 'claims', ['run_id'], unique=False)
    op.create_index('ix_claims_run_type', 'claims', ['run_id', 'claim_type'], unique=False)
    op.create_index(op.f('ix_claims_status'), 'claims', ['status'], unique=False)
    op.create_table('conflicts',
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('result_id', sa.String(length=32), nullable=True),
    sa.Column('claim_type', sa.String(length=60), nullable=False),
    sa.Column('unresolved', sa.Boolean(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conflicts_result_id'), 'conflicts', ['result_id'], unique=False)
    op.create_index(op.f('ix_conflicts_run_id'), 'conflicts', ['run_id'], unique=False)
    op.create_index(op.f('ix_conflicts_unresolved'), 'conflicts', ['unresolved'], unique=False)
    op.create_table('program_results',
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('dedupe_key', sa.String(length=400), nullable=False),
    sa.Column('university', sa.String(length=200), nullable=False),
    sa.Column('university_key', sa.String(length=300), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('program', sa.String(length=300), nullable=False),
    sa.Column('eligibility', sa.String(length=40), nullable=False),
    sa.Column('admissions_fit', sa.String(length=40), nullable=False),
    sa.Column('funding_fit', sa.String(length=40), nullable=False),
    sa.Column('funding_classification', sa.String(length=40), nullable=False),
    sa.Column('score_total', sa.Float(), nullable=False),
    sa.Column('user_decision', sa.String(length=20), nullable=False),
    sa.Column('user_decision_reason', sa.Text(), nullable=False),
    sa.Column('user_notes', sa.Text(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('checklist', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_results_admissions_fit'), 'program_results', ['admissions_fit'], unique=False)
    op.create_index(op.f('ix_program_results_country'), 'program_results', ['country'], unique=False)
    op.create_index(op.f('ix_program_results_dedupe_key'), 'program_results', ['dedupe_key'], unique=False)
    op.create_index(op.f('ix_program_results_eligibility'), 'program_results', ['eligibility'], unique=False)
    op.create_index(op.f('ix_program_results_funding_classification'), 'program_results', ['funding_classification'], unique=False)
    op.create_index(op.f('ix_program_results_funding_fit'), 'program_results', ['funding_fit'], unique=False)
    op.create_index(op.f('ix_program_results_run_id'), 'program_results', ['run_id'], unique=False)
    op.create_index(op.f('ix_program_results_score_total'), 'program_results', ['score_total'], unique=False)
    op.create_index(op.f('ix_program_results_university_key'), 'program_results', ['university_key'], unique=False)
    op.create_index(op.f('ix_program_results_user_decision'), 'program_results', ['user_decision'], unique=False)
    op.create_index('ix_results_dedupe', 'program_results', ['run_id', 'dedupe_key'], unique=True)
    op.create_index('ix_results_run_decision', 'program_results', ['run_id', 'user_decision'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_results_run_decision', table_name='program_results')
    op.drop_index('ix_results_dedupe', table_name='program_results')
    op.drop_index(op.f('ix_program_results_user_decision'), table_name='program_results')
    op.drop_index(op.f('ix_program_results_university_key'), table_name='program_results')
    op.drop_index(op.f('ix_program_results_score_total'), table_name='program_results')
    op.drop_index(op.f('ix_program_results_run_id'), table_name='program_results')
    op.drop_index(op.f('ix_program_results_funding_fit'), table_name='program_results')
    op.drop_index(op.f('ix_program_results_funding_classification'), table_name='program_results')
    op.drop_index(op.f('ix_program_results_eligibility'), table_name='program_results')
    op.drop_index(op.f('ix_program_results_dedupe_key'), table_name='program_results')
    op.drop_index(op.f('ix_program_results_country'), table_name='program_results')
    op.drop_index(op.f('ix_program_results_admissions_fit'), table_name='program_results')
    op.drop_table('program_results')
    op.drop_index(op.f('ix_conflicts_unresolved'), table_name='conflicts')
    op.drop_index(op.f('ix_conflicts_run_id'), table_name='conflicts')
    op.drop_index(op.f('ix_conflicts_result_id'), table_name='conflicts')
    op.drop_table('conflicts')
    op.drop_index(op.f('ix_claims_status'), table_name='claims')
    op.drop_index('ix_claims_run_type', table_name='claims')
    op.drop_index(op.f('ix_claims_run_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_result_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_claim_type'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_research_runs_worker_id'), table_name='research_runs')
    op.drop_index(op.f('ix_research_runs_stage'), table_name='research_runs')
    op.drop_index(op.f('ix_research_runs_profile_id'), table_name='research_runs')
    op.drop_table('research_runs')
    op.drop_table('schema_version')
    op.drop_index('ix_jobs_run', table_name='jobs')
    op.drop_index('ix_jobs_lease', table_name='jobs')
    op.drop_index('ix_jobs_claimable', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_index('ix_audit_entity', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('applicant_profiles')
    # ### end Alembic commands ###
