import type { Locale } from './i18n';

/** Only presentation copy: never use translated labels as API enum values. */
export const profileCopy = {
  "Nothing here is converted or inferred behind your back. Grades keep their original scale, and every blank below is listed with exactly what it costs you in the results.": { en: "Nothing here is converted or inferred behind your back. Grades keep their original scale, and every blank below is listed with exactly what it costs you in the results.", ru: "Оценки сохраняются в исходной шкале, без скрытых преобразований. Проверка показывает, какие данные стоит дополнить и как пробелы влияют на результаты.", kk: "Бағалар жасырын түрлендірусіз бастапқы шкалада сақталады. Тексеру қандай деректерді толықтыру керегін және олқылықтардың нәтижелерге әсерін көрсетеді." },
  "Unsaved changes restored.": { en: "Unsaved changes restored.", ru: "Несохранённые изменения восстановлены.", kk: "Сақталмаған өзгерістер қалпына келтірілді." },
  "This browser still had edits you had not saved. Your saved profile on the server is untouched until you press Save.": { en: "This browser still had edits you had not saved. Your saved profile on the server is untouched until you press Save.", ru: "В браузере остались ваши правки. Профиль на сервере не изменится, пока вы не нажмёте «Сохранить профиль».", kk: "Браузерде өзгерістеріңіз сақталған. «Профильді сақтау» батырмасын басқанша сервердегі профиль өзгермейді." },
  "Loaded saved profile:": { en: "Loaded saved profile:", ru: "Загружен сохранённый профиль:", kk: "Сақталған профиль жүктелді:" },
  "Edits here update that profile.": { en: "Edits here update that profile.", ru: "Правки относятся к этому профилю.", kk: "Өзгерістер осы профильге қатысты." },
  "Replace the profile you have saved?": { en: "Replace the profile you have saved?", ru: "Заменить текущую анкету?", kk: "Ағымдағы сауалнаманы ауыстыру керек пе?" },
  "The saved copy is not deleted, but your unsaved edits are lost.": { en: "The saved copy is not deleted, but your unsaved edits are lost.", ru: "Сохранённая копия не удалится, но несохранённые правки будут потеряны.", kk: "Сақталған көшірме жойылмайды, бірақ сақталмаған өзгерістер жоғалады." },
  "Use this": { en: "Use this", ru: "Использовать", kk: "Қолдану" },
  "Programmes that publish a different scale cannot be decided without a conversion. You can accept one — the method and its caveat are stored with the number.": { en: "Programmes that publish a different scale cannot be decided without a conversion. You can accept one — the method and its caveat are stored with the number.", ru: "Для сопоставления с программами, использующими другую шкалу, нужен перевод оценок. Вы можете подтвердить метод — он и его ограничения сохранятся вместе с оценкой.", kk: "Басқа шкаланы қолданатын бағдарламалармен салыстыру үшін бағаларды түрлендіру қажет. Әдісті растай аласыз — ол және оның шектеулері бағамен бірге сақталады." },
  "Converted to": { en: "Converted to", ru: "Переведено в шкалу", kk: "Түрлендірілген шкала" },
  "Convert to": { en: "Convert to", ru: "Перевести в шкалу", kk: "Шкалаға түрлендіру" },
  "The conversion was not applied.": { en: "The conversion was not applied.", ru: "Перевод оценки не выполнен.", kk: "Баға түрлендірілмеді." },
  "Your grade is unchanged.": { en: "Your grade is unchanged.", ru: "Ваша оценка не изменилась.", kk: "Бағаңыз өзгерген жоқ." },
  "That file could not be read.": { en: "That file could not be read.", ru: "Не удалось прочитать файл.", kk: "Файлды оқу мүмкін болмады." },
  "The conversion could not be applied.": { en: "The conversion could not be applied.", ru: "Не удалось применить перевод оценки.", kk: "Бағаны түрлендіру мүмкін болмады." },
  "National level": { en: "national", ru: "Национальный", kk: "Ұлттық" },
  "out of": { en: "out of", ru: "из", kk: "/" },
  "Level": { en: "Level", ru: "Уровень", kk: "Деңгей" },
  "Field of study": { en: "Field of study", ru: "Направление обучения", kk: "Оқу бағыты" },
  "Intake term": { en: "Intake term", ru: "Семестр поступления", kk: "Қабылдау семестрі" },
  "Intake year": { en: "Intake year", ru: "Год поступления", kk: "Қабылдау жылы" },
  "Citizenship": { en: "Citizenship", ru: "Гражданство", kk: "Азаматтық" },
  "Country of residence": { en: "Country of residence", ru: "Страна проживания", kk: "Тұратын ел" },
  "Country of education": { en: "Country of education", ru: "Страна обучения", kk: "Білім алған ел" },
  "Additional nationality (if any)": { en: "Additional nationality (if any)", ru: "Дополнительное гражданство (если есть)", kk: "Қосымша азаматтық (бар болса)" },
  "Education system": { en: "Education system", ru: "Система образования", kk: "Білім беру жүйесі" },
  "Curriculum type": { en: "Curriculum type", ru: "Учебная программа", kk: "Оқу бағдарламасы" },
  "Finishing school on": { en: "Finishing school on", ru: "Дата окончания школы", kk: "Мектеп бітіру күні" },
  "Transcript (PDF)": { en: "Transcript (PDF)", ru: "Выписка оценок (PDF)", kk: "Бағалар үзіндісі (PDF)" },
  "GPA / average": { en: "GPA / average", ru: "GPA / средний балл", kk: "GPA / орташа балл" },
  "Maximum on your scale": { en: "Maximum on your scale", ru: "Максимум шкалы оценок", kk: "Бағалау шкаласының максимумы" },
  "Scale name": { en: "Scale name", ru: "Название шкалы", kk: "Шкала атауы" },
  "Class rank": { en: "Class rank", ru: "Место в классе", kk: "Сыныптағы орны" },
  "Class size": { en: "Class size", ru: "Количество учеников в классе", kk: "Сыныптағы оқушылар саны" },
  "Planned retakes": { en: "Planned retakes", ru: "Запланированные пересдачи", kk: "Жоспарланған қайта тапсырулар" },
  "Test name": { en: "Test name", ru: "Название экзамена", kk: "Емтихан атауы" },
  "Score": { en: "Score", ru: "Балл", kk: "Балл" },
  "Maximum": { en: "Maximum", ru: "Максимум", kk: "Максимум" },
  "Taken on": { en: "Taken on", ru: "Дата сдачи", kk: "Тапсырған күні" },
  "Planned retake": { en: "Planned retake", ru: "Дата пересдачи", kk: "Қайта тапсыру күні" },
  "Subject": { en: "Subject", ru: "Предмет", kk: "Пән" },
  "Grade": { en: "Grade", ru: "Оценка", kk: "Баға" },
  "Scale maximum": { en: "Scale maximum", ru: "Максимум шкалы", kk: "Шкала максимумы" },
  "Scale label": { en: "Scale label", ru: "Название шкалы", kk: "Шкала атауы" },
  "Framework": { en: "Framework", ru: "Программа", kk: "Бағдарлама" },
  "Result": { en: "Result", ru: "Результат", kk: "Нәтиже" },
  "Year": { en: "Year", ru: "Год", kk: "Жыл" },
  "Activity": { en: "Activity", ru: "Занятие", kk: "Іс-әрекет" },
  "Category": { en: "Category", ru: "Категория", kk: "Санат" },
  "Role": { en: "Role", ru: "Роль", kk: "Рөл" },
  "Responsibility": { en: "Responsibility", ru: "Уровень ответственности", kk: "Жауапкершілік деңгейі" },
  "Months": { en: "Months", ru: "Месяцев", kk: "Ай саны" },
  "Hours / week": { en: "Hours / week", ru: "Часов в неделю", kk: "Аптасына сағат" },
  "Weeks / year": { en: "Weeks / year", ru: "Недель в году", kk: "Жылына апта" },
  "Measurable outcome": { en: "Measurable outcome", ru: "Измеримый результат", kk: "Өлшенетін нәтиже" },
  "Impact on others": { en: "Impact on others", ru: "Влияние на других", kk: "Басқаларға әсері" },
  "Evidence links": { en: "Evidence links", ru: "Ссылки на подтверждения", kk: "Растайтын сілтемелер" },
  "Evidence link": { en: "Evidence link", ru: "Ссылка на подтверждение", kk: "Растайтын сілтеме" },
  "+ Add evidence link": { en: "+ Add evidence link", ru: "+ Добавить ссылку", kk: "+ Сілтеме қосу" },
  "Remove link": { en: "Remove link", ru: "Удалить ссылку", kk: "Сілтемені жою" },
  "Add up to five full HTTP or HTTPS URLs. Format is checked locally; links are not verified.": { en: "Add up to five full HTTP or HTTPS URLs. Format is checked locally; links are not verified.", ru: "Добавьте до пяти полных HTTP- или HTTPS-ссылок. Проверяется только формат; содержимое ссылки не подтверждено.", kk: "Беске дейін толық HTTP немесе HTTPS сілтемесін қосыңыз. Тек пішімі тексеріледі; сілтеме мазмұны расталмаған." },
  "Enter a full HTTP or HTTPS URL.": { en: "Enter a full HTTP or HTTPS URL.", ru: "Введите полную ссылку с HTTP или HTTPS.", kk: "HTTP немесе HTTPS арқылы толық сілтемені енгізіңіз." },
  "Five link limit reached.": { en: "Five link limit reached.", ru: "Можно добавить не более пяти ссылок.", kk: "Бес сілтемеден артық қосуға болмайды." },
  "Achievement": { en: "Achievement", ru: "Достижение", kk: "Жетістік" },
  "Placement": { en: "Placement", ru: "Занятое место", kk: "Иеленген орын" },
  "Selection criterion": { en: "Selection criterion", ru: "Критерий отбора", kk: "Іріктеу өлшемі" },
  "Start from": { en: "Start from", ru: "С чего начать", kk: "Неден бастау керек" },
  "Application context": { en: "Application context", ru: "О поступлении", kk: "Оқуға түсу туралы" },
  "Read it off your transcript": { en: "Read it off your transcript", ru: "Импорт из выписки оценок", kk: "Бағалар үзіндісінен импорттау" },
  "Grades": { en: "Grades", ru: "Оценки", kk: "Бағалар" },
  "Other tests and planned retakes": { en: "Other tests and planned retakes", ru: "Другие экзамены и пересдачи", kk: "Басқа емтихандар және қайта тапсырулар" },
  "Subject grades": { en: "Subject grades", ru: "Оценки по предметам", kk: "Пәндер бойынша бағалар" },
  "AP, IB and A-Level results": { en: "AP, IB and A-Level results", ru: "Результаты AP, IB и A-Level", kk: "AP, IB және A-Level нәтижелері" },
  "Extracurricular activities": { en: "Extracurricular activities", ru: "Внеучебная деятельность", kk: "Сабақтан тыс іс-әрекеттер" },
  "Achievements": { en: "Achievements", ru: "Достижения", kk: "Жетістіктер" },
  "What is missing, and what it costs you": { en: "What is missing, and what it costs you", ru: "Что стоит дополнить и на что это влияет", kk: "Нені толықтыру керек және оның әсері" },
  "Demo data is never loaded on your behalf. Choose it explicitly, and it is clearly labelled everywhere it appears.": { en: "Demo data is never loaded on your behalf. Choose it explicitly, and it is clearly labelled everywhere it appears.", ru: "Демоданные можно загрузить отдельной кнопкой. Они помечаются как демонстрационные.", kk: "Демодеректерді жеке батырмамен жүктеуге болады. Олар демонстрациялық деп белгіленеді." },
  "What you are applying for, and from where.": { en: "What you are applying for, and from where.", ru: "Куда вы поступаете и где учились.", kk: "Қайда оқуға түсесіз және қайда оқыдыңыз." },
  "Drives which programmes are searched.": { en: "Drives which programmes are searched.", ru: "Определяет, какие программы искать.", kk: "Қандай бағдарламаларды іздеу керегін анықтайды." },
  "Decides which scholarships you are eligible for at all.": { en: "Decides which scholarships you are eligible for at all.", ru: "Влияет на доступность стипендий.", kk: "Қандай стипендияларға өтініш бере алатыныңызға әсер етеді." },
  "Leave blank if none.": { en: "Leave blank if none.", ru: "Оставьте пустым, если нет.", kk: "Жоқ болса, бос қалдырыңыз." },
  "Optional. The file is read and discarded — it is never saved, and nothing is filled in until you say so.": { en: "Optional. The file is read and discarded — it is never saved, and nothing is filled in until you say so.", ru: "Необязательно. Файл обрабатывается без сохранения. Данные попадут в анкету только после вашего подтверждения.", kk: "Міндетті емес. Файл сақталмай өңделеді. Деректер сауалнамаға тек сіз растағаннан кейін енгізіледі." },
  "Enter the grade exactly as it appears on your transcript. ASHYQ Apply does not convert it silently.": { en: "Enter the grade exactly as it appears on your transcript. ASHYQ Apply does not convert it silently.", ru: "Введите оценку как в выписке. ASHYQ Apply не переводит её в другую шкалу без вашего согласия.", kk: "Бағаны үзіндіде көрсетілгендей енгізіңіз. ASHYQ Apply оны келісіміңізсіз басқа шкалаға ауыстырмайды." },
  "e.g. 'KZ 5-point', 'US 4.0 unweighted'": { en: "e.g. 'KZ 5-point', 'US 4.0 unweighted'", ru: "Например: 'KZ 5-point', 'US 4.0 unweighted'", kk: "Мысалы: 'KZ 5-point', 'US 4.0 unweighted'" },
  "Optional. Keep achieved and planned results separate.": { en: "Optional. Keep achieved and planned results separate.", ru: "Необязательно. Указывайте полученные результаты отдельно от планов.", kk: "Міндетті емес. Алынған нәтижелерді жоспарлардан бөлек көрсетіңіз." },
  "Comma-separated.": { en: "Comma-separated.", ru: "Через запятую.", kk: "Үтірмен бөліңіз." },
  "Keep the original transcript scale for every subject.": { en: "Keep the original transcript scale for every subject.", ru: "Сохраняйте исходную шкалу оценок для каждого предмета.", kk: "Әр пән үшін бастапқы бағалау шкаласын сақтаңыз." },
  "Add achieved and predicted curriculum results exactly as reported.": { en: "Add achieved and predicted curriculum results exactly as reported.", ru: "Укажите полученные и прогнозируемые результаты как в документе.", kk: "Алынған және болжамды нәтижелерді құжаттағыдай көрсетіңіз." },
  "Depth, responsibility and measurable impact matter more than a long list.": { en: "Depth, responsibility and measurable impact matter more than a long list.", ru: "Важнее глубина участия, ответственность и измеримый вклад, а не длина списка.", kk: "Тізімнің ұзындығынан гөрі қатысу тереңдігі, жауапкершілік және өлшенетін үлес маңызды." },
  "Comma-separated URLs.": { en: "Comma-separated URLs.", ru: "Ссылки через запятую.", kk: "Сілтемелерді үтірмен бөліңіз." },
  "Include level, placement and how recipients were selected.": { en: "Include level, placement and how recipients were selected.", ru: "Укажите уровень, занятое место и критерии отбора.", kk: "Деңгейді, иеленген орынды және іріктеу өлшемдерін көрсетіңіз." },
  "Blocks research": { en: "Blocks research", ru: "Блокирует исследование", kk: "Зерттеуді бөгейді" },
  "Strong effect on results": { en: "Strong effect on results", ru: "Сильно влияет на результаты", kk: "Нәтижелерге қатты әсер етеді" },
  "Noticeable effect": { en: "Noticeable effect", ru: "Заметное влияние", kk: "Елеулі әсер" },
  "Minor effect": { en: "Minor effect", ru: "Небольшое влияние", kk: "Шағын әсер" },
  "Foundation": { en: "Foundation", ru: "Подготовительная программа", kk: "Дайындық бағдарламасы" },
  "Bachelor": { en: "Bachelor", ru: "Бакалавриат", kk: "Бакалавриат" },
  "Master": { en: "Master", ru: "Магистратура", kk: "Магистратура" },
  "PhD": { en: "PhD", ru: "Докторантура (PhD)", kk: "Докторантура (PhD)" },
  "Fall": { en: "Fall", ru: "Осень", kk: "Күз" },
  "Spring": { en: "Spring", ru: "Весна", kk: "Көктем" },
  "Summer": { en: "Summer", ru: "Лето", kk: "Жаз" },
  "Winter": { en: "Winter", ru: "Зима", kk: "Қыс" },
  "national": { en: "national", ru: "Национальная", kk: "Ұлттық" },
  "ib": { en: "ib", ru: "IB", kk: "IB" },
  "a_level": { en: "a_level", ru: "A-Level", kk: "A-Level" },
  "ap": { en: "ap", ru: "AP", kk: "AP" },
  "us_high_school": { en: "us_high_school", ru: "Школа США", kk: "АҚШ мектебі" },
  "other": { en: "other", ru: "Другое", kk: "Басқа" },
  "participant": { en: "participant", ru: "Участник", kk: "Қатысушы" },
  "contributor": { en: "contributor", ru: "Исполнитель", kk: "Орындаушы" },
  "coordinator": { en: "coordinator", ru: "Координатор", kk: "Үйлестіруші" },
  "leader": { en: "leader", ru: "Руководитель", kk: "Жетекші" },
  "founder": { en: "founder", ru: "Основатель", kk: "Негізін қалаушы" },
  "school": { en: "school", ru: "Школьный", kk: "Мектептік" },
  "city": { en: "city", ru: "Городской", kk: "Қалалық" },
  "regional": { en: "regional", ru: "Региональный", kk: "Өңірлік" },
  "international": { en: "international", ru: "Международный", kk: "Халықаралық" },
  "Who is applying": { en: "Who is applying", ru: "Профиль абитуриента", kk: "Талапкер профилі" },
  "Step 01": { en: "Step 01", ru: "Шаг 01", kk: "01-қадам" },
  "Blank profile": { en: "Blank profile", ru: "Пустая анкета", kk: "Бос сауалнама" },
  "Load synthetic demo": { en: "Load synthetic demo", ru: "Загрузить демопример", kk: "Демомысалды жүктеу" },
  "synthetic demo data": { en: "synthetic demo data", ru: "вымышленные демоданные", kk: "ойдан шығарылған демодеректер" },
  "Replace": { en: "Replace", ru: "Заменить", kk: "Ауыстыру" },
  "Keep editing": { en: "Keep editing", ru: "Продолжить редактирование", kk: "Өңдеуді жалғастыру" },
  "Discard these edits": { en: "Discard these edits", ru: "Отменить эти изменения", kk: "Осы өзгерістерден бас тарту" },
  "Reading…": { en: "Reading…", ru: "Читаем файл…", kk: "Файл оқылуда…" },
  "Apply": { en: "Apply", ru: "Применить", kk: "Қолдану" },
  "Remove": { en: "Remove", ru: "Удалить", kk: "Жою" },
  "+ Add another test": { en: "+ Add another test", ru: "+ Добавить экзамен", kk: "+ Емтихан қосу" },
  "+ Add subject grade": { en: "+ Add subject grade", ru: "+ Добавить оценку по предмету", kk: "+ Пән бағасын қосу" },
  "+ Add curriculum result": { en: "+ Add curriculum result", ru: "+ Добавить результат программы", kk: "+ Бағдарлама нәтижесін қосу" },
  "Predicted": { en: "Predicted", ru: "Прогнозируемый результат", kk: "Болжамды нәтиже" },
  "Remove activity": { en: "Remove activity", ru: "Удалить занятие", kk: "Іс-әрекетті жою" },
  "+ Add activity": { en: "+ Add activity", ru: "+ Добавить занятие", kk: "+ Іс-әрекет қосу" },
  "+ Add achievement": { en: "+ Add achievement", ru: "+ Добавить достижение", kk: "+ Жетістік қосу" },
  "Saving…": { en: "Saving…", ru: "Сохраняем…", kk: "Сақталуда…" },
  "Save profile": { en: "Save profile", ru: "Сохранить профиль", kk: "Профильді сақтау" },
  "Saved": { en: "Saved", ru: "Сохранено", kk: "Сақталды" },
  "Next: preferences & budget →": { en: "Next: preferences & budget →", ru: "Далее: предпочтения и бюджет →", kk: "Келесі: қалаулар мен бюджет →" },
  "No gaps found by the current server checks.": { en: "No gaps found by the current server checks.", ru: "Текущая проверка сервера не обнаружила пробелов.", kk: "Сервердің ағымдағы тексеруі олқылықтарды таппады." },
} as const;

export type ProfileCopyKey = keyof typeof profileCopy;
export const translateProfile = (locale: Locale, key: ProfileCopyKey): string => profileCopy[key][locale];
