import type { Locale } from './i18n';

const ru = {
  unavailable: 'Нет данных',
  case: 'Мой кейс', shortlist: 'Подбор', plan: 'План', community: 'Сообщество', more: 'Ещё',
  navigation: 'Основная навигация', sections: 'В этом разделе', skip: 'Перейти к содержимому',
  chapter: 'Ваша следующая глава', title: 'Большой путь. Понятный следующий шаг.',
  intro: 'Профиль, подбор и подготовка к поступлению — в одном месте. Двигайтесь в своём темпе, опираясь на подтверждённые данные.',
  next: 'Следующий шаг', prepare: 'Расскажите о себе', prepareBody: 'Начните с направления, оценок и английского. Сохранённый профиль станет основой исследования.',
  edit: 'Заполнить профиль', preferences: 'Настроить приоритеты', preferencesBody: 'Определите страны и бюджет, затем запустите исследование официальных источников.',
  working: 'Исследование продолжается', workingBody: 'Можно перейти в другой раздел. Ход работы всегда доступен здесь.', progress: 'Открыть ход исследования',
  failed: 'Исследованию нужно внимание', failedBody: 'Посмотрите, что остановило работу, и доступные действия для продолжения.',
  ready: 'Первые варианты уже здесь', readyBody: 'Изучите требования и источники. Сохраните подходящие программы, чтобы перейти к плану документов.',
  review: 'Посмотреть подбор', route: 'Ваш маршрут', profile: 'Профиль', research: 'Исследование', documents: 'Подготовка',
  profileHint: 'Ваши достижения и цели', researchHint: 'Программы и официальные источники', documentsHint: 'Решения, документы и сроки',
  saved: 'Сохранён', draft: 'Черновик', notStarted: 'Ещё не начато', available: 'Есть результаты',
  overview: 'Что уже собрано', programmes: 'Программ в подборе', selected: 'Сохранено для решения', questions: 'Вопросов к источникам',
  evidence: 'Сначала факты. Затем решение.', evidenceBody: 'Требования, стоимость и сроки проверяются по официальным страницам. Если данных нет, это остаётся открытым вопросом.',
  modeDemo: 'Демо-данные', modeLive: 'Живые источники', connecting: 'Подключение…', applicant: 'Кейс',
  savedNote: 'Ваши сохранённые данные доступны в профиле.', draftNote: 'В профиле есть несохранённые изменения.',
};
type Copy = { [K in keyof typeof ru]: string };
const en: Copy = {
  unavailable: 'Unavailable',
  case: 'My case', shortlist: 'Shortlist', plan: 'Plan', community: 'Community', more: 'More',
  navigation: 'Main navigation', sections: 'In this section', skip: 'Skip to content',
  chapter: 'Your next chapter', title: 'A big journey. A clear next step.',
  intro: 'Your profile, research and preparation in one place. Move at your own pace, guided by verified information.',
  next: 'Next step', prepare: 'Tell us about yourself', prepareBody: 'Start with your subject, grades and English. Your saved profile will guide the research.',
  edit: 'Complete your profile', preferences: 'Set your priorities', preferencesBody: 'Choose countries and a budget, then start researching official sources.',
  working: 'Research is in progress', workingBody: 'You can visit another section. Progress is always available here.', progress: 'View research progress',
  failed: 'Research needs attention', failedBody: 'Review what stopped the research and the available ways to continue.',
  ready: 'Your first options are here', readyBody: 'Read the requirements and sources. Save suitable programmes to start preparing documents.',
  review: 'Review the shortlist', route: 'Your route', profile: 'Profile', research: 'Research', documents: 'Preparation',
  profileHint: 'Your achievements and goals', researchHint: 'Programmes and official sources', documentsHint: 'Decisions, documents and deadlines',
  saved: 'Saved', draft: 'Draft', notStarted: 'Not started', available: 'Results available',
  overview: 'Your case so far', programmes: 'Programmes found', selected: 'Saved for consideration', questions: 'Questions about sources',
  evidence: 'Facts first. Then a decision.', evidenceBody: 'Requirements, costs and dates are checked against official pages. Missing information stays an open question.',
  modeDemo: 'Demo data', modeLive: 'Live sources', connecting: 'Connecting…', applicant: 'Case',
  savedNote: 'Your saved information is available in your profile.', draftNote: 'Your profile has unsaved changes.',
};
const kk: Copy = {
  unavailable: 'Дерек жоқ',
  case: 'Менің ісім', shortlist: 'Іріктеу', plan: 'Жоспар', community: 'Қауымдастық', more: 'Тағы',
  navigation: 'Негізгі навигация', sections: 'Осы бөлімде', skip: 'Мазмұнға өту',
  chapter: 'Сіздің келесі тарауыңыз', title: 'Үлкен жол. Түсінікті келесі қадам.',
  intro: 'Профиль, зерттеу және оқуға түсуге дайындық — бір жерде. Расталған деректерге сүйеніп, өз қарқыныңызбен жүріңіз.',
  next: 'Келесі қадам', prepare: 'Өзіңіз туралы айтыңыз', prepareBody: 'Мамандық, бағалар және ағылшын тілінен бастаңыз. Сақталған профиль зерттеуге негіз болады.',
  edit: 'Профильді толтыру', preferences: 'Басымдықтарды таңдау', preferencesBody: 'Елдер мен бюджетті таңдап, ресми дереккөздерді зерттеуді бастаңыз.',
  working: 'Зерттеу жүріп жатыр', workingBody: 'Басқа бөлімге өте аласыз. Жұмыс барысы әрқашан осында қолжетімді.', progress: 'Зерттеу барысын ашу',
  failed: 'Зерттеуге назар аудару қажет', failedBody: 'Жұмыс неге тоқтағанын және жалғастыру жолдарын қараңыз.',
  ready: 'Алғашқы нұсқалар дайын', readyBody: 'Талаптар мен дереккөздерді оқыңыз. Құжаттарды дайындау үшін сәйкес бағдарламаларды сақтаңыз.',
  review: 'Іріктеуді қарау', route: 'Сіздің бағытыңыз', profile: 'Профиль', research: 'Зерттеу', documents: 'Дайындық',
  profileHint: 'Жетістіктеріңіз бен мақсаттарыңыз', researchHint: 'Бағдарламалар және ресми дереккөздер', documentsHint: 'Шешімдер, құжаттар және мерзімдер',
  saved: 'Сақталған', draft: 'Жоба', notStarted: 'Әлі басталмаған', available: 'Нәтижелер бар',
  overview: 'Жиналған деректер', programmes: 'Табылған бағдарламалар', selected: 'Қарастыруға сақталған', questions: 'Дереккөздерге сұрақтар',
  evidence: 'Алдымен деректер. Содан кейін шешім.', evidenceBody: 'Талаптар, құн және мерзімдер ресми беттерден тексеріледі. Ақпарат болмаса, сұрақ ашық қалады.',
  modeDemo: 'Демо-деректер', modeLive: 'Ресми дереккөздер', connecting: 'Қосылуда…', applicant: 'Іс',
  savedNote: 'Сақталған деректеріңіз профильде қолжетімді.', draftNote: 'Профильде сақталмаған өзгерістер бар.',
};
export const redesignCopy: Record<Locale, Copy> = { ru, en, kk };
